version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: docker/Dockerfile.crawler
    environment:
      - CONFIG_PATH=config/production.yaml
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile.indexer
    environment:
      - CONFIG_PATH=config/production.yaml
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  search-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/production.yaml
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: searchengine
      POSTGRES_USER: searchuser
      POSTGRES_PASSWORD: searchpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
